// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Game(Props) {
  return React.createElement("div", {
              style: {
                background: "red",
                fontSize: "68px"
              }
            }, "Hello ReScripters hedy!");
}

var make = Game;

exports.make = make;
/* react Not a pure module */
