// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Greeting(Props) {
  return React.createElement("div", undefined, "Hello ReScripters hey!");
}

var make = Greeting;

exports.make = make;
/* react Not a pure module */
