// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Curry = require("rescript/lib/js/curry.js");

Jest.describe("Expect", (function (param) {
        return Jest.test("toBe", (function (param) {
                      return Jest.Expect.toBe(Jest.Expect.expect(3), 3);
                    }));
      }));

Jest.describe("Expect.Operators", (function (param) {
        return Jest.test("==", (function (param) {
                      return Curry._2(Jest.Expect.Operators.$eq$eq, Jest.Expect.expect(3), 3);
                    }));
      }));

/*  Not a pure module */
